language: php
dist: trusty
sudo: required

php:
  - 7.0

before_install:
  - cp .env.travis .env.testing
  - mysql -e 'create database testing;'

install:
  - composer install --no-interaction

before_script:
  - php artisan key:generate --env=testing
  - php artisan migrate --env=testing

  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - php artisan selenium:start >>storage/selenium.log 2>&1 &
  - php artisan serve --env=testing >/dev/null 2>&1 &
  - sleep 10

script:
  - vendor/bin/phpunit --verbose

after_failure:
  - tail -n 10000 storage/logs/laravel.log | pastebinit
  - tail -n 10000 storage/logs/selenium.log | pastebinit

services:
  - mysql

env:
  - DEFAULT_BROWSER=chrome

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
    - pastebinit

cache:
  directories:
    - vendor
