language: php

php:
  - 7.1

before_install:
  - cp .env.travis .env.testing
  - mysql -e 'create database testing;'

install:
  - composer install --no-interaction

before_script:
  - php artisan key:generate --env=testing
  - php artisan migrate --env=testing

  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - php artisan selenium:start &
  - php artisan serve --env=testing &
  - sleep 3

script:
  - vendor/bin/phpunit

services:
  - mysql

cache:
  directories:
    - vendor