language: php

php:
  - 7.1

before_install:
  - cp .env.travis .env
  - mysql -e 'create database travis_test;'

install:
  - composer install --no-interaction

before_script:
  - php artisan key:generate
  - php artisan migrate

  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - php artisan selenium:start &
  - php artisan serve &
  - sleep 3

script:
  - vendor/bin/phpunit

services:
  - mysql

cache:
  directories:
    - vendor